### ISSUE TITLE
Segmentation Violation while launching whatscli in the terminal

### ISSUE THREAD

**Issue by smabbasht** [normen/whatscli#87]
Hello, 
I have cloned the Aur repository on my Arch Linux and it gave this error when I launched it in my terminal. 
![Screenshot from 2023-01-07 09-45-31](https://user-images.githubusercontent.com/79911677/211133161-ea79c7d4-bbfc-4569-9414-d095ac697b75.png)
Let me know if there's anything I am missing or if you need anymore information. I'll be happy to share... Thanks

**Comment by doruksahin** [comment]
same

**Comment by almeida-caio** [comment]
I suggest to take a look at the issue #72, just to get some context around the problem. (:

That being said, I believe the version in AUR is somewhat outdated and, even if it was up-to-date, the problem would probably still be there, since the releases contained in this repo have a hard time with the connection.

You can get a 'working' version by building it yourself from the source at the `whatsmeow` branch. However, as far as I know, it's a work in progress, so some features might be missing and you should not expect it to run flawlessly.

**Comment by normen** [comment]
What he said, the current "stable" version uses the old whatsapp library which only works with some old accounts that still have no multiclient enabled and crashes with most others. The whatsmeow branch is not working yet and will probably look different code-wise than it does now. Still no guarantees on when I get around to do this though.

**Comment by smabbasht** [comment]
The branch whatsmeow does work for me, Thanks
